- name: migrate-weblogic-ejb-deployment-descriptor
  description: Migrate weblogic-ejb-jar.xml deployment descriptor
  order: 89
  condition:
    type: org.springframework.sbm.common.migration.conditions.FileExist
    fileName: weblogic-ejb-jar.xml


  actions:
    - type: org.springframework.sbm.jee.wls.actions.MigrateWlsEjbDeploymentDescriptor
      condition:
        type: org.springframework.sbm.common.migration.conditions.FileExist
        fileName: weblogic-ejb-jar.xml
      description: Migrate weblogic-ejb-jar.xml deployment descriptor